# -*- coding: utf-8 -*-

from mathics.core.symbols import Symbol

# Some other common Symbols. This list is sorted in alphabetic order.
SymbolAborted = Symbol("$Aborted")
SymbolAlternatives = Symbol("Alternatives")
SymbolAssociation = Symbol("Association")
SymbolBlank = Symbol("Blank")
SymbolByteArray = Symbol("ByteArray")
SymbolComplexInfinity = Symbol("ComplexInfinity")
SymbolD = Symbol("D")
SymbolDirectedInfinity = Symbol("DirectedInfinity")
SymbolDivide = Symbol("Divide")
SymbolFailed = Symbol("$Failed")
SymbolGreater = Symbol("Greater")
SymbolIndeterminate = Symbol("Indeterminate")
SymbolInfinity = Symbol("Infinity")
SymbolInfix = Symbol("Infix")
SymbolInteger = Symbol("Integer")
SymbolLeft = Symbol("Left")
SymbolLess = Symbol("Less")
SymbolMachinePrecision = Symbol("MachinePrecision")
SymbolMakeBoxes = Symbol("MakeBoxes")
SymbolMinus = Symbol("Minus")
SymbolPattern = Symbol("Pattern")
SymbolPlus = Symbol("Plus")
SymbolPower = Symbol("Power")
SymbolRational = Symbol("Rational")
SymbolRowBox = Symbol("RowBox")
SymbolRule = Symbol("Rule")
SymbolSequence = Symbol("Sequence")
SymbolSeries = Symbol("Series")
SymbolSeriesData = Symbol("SeriesData")
SymbolTimes = Symbol("Times")
SymbolUndefined = Symbol("Undefined")
